horizon: 5
gamma: 0.8
size: 100
iteration: 0
run_tag: "20250719"
num_basis_knots: 20
spline_degree: 5
num_action_grid_points: 100
lambda_grid_size: 10
lambda_min: 0.00001
lambda_max: 0.1
num_data_subjects: 100
num_cv_splits: 3
fqi_iterations: 10
training_iterations: 2000
fqe_simulations: 1000
fqe_cycles: 20
fqe_eval_states: 100
fqe_train_expectation_samples: 1000
fqe_eval_expectation_samples: 1000
fqe_clamp_targets: true
learning_rate: 0.01
early_stopping_patience: 50
early_stopping_delta: 0.0001
